//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Runtime.InteropServices;
    using System.Diagnostics.CodeAnalysis;
    
    internal static unsafe partial class libcef
    {
        public const string CEF_VERSION = "150.0.25-2026-08-04-surface-lease.3558+g3e666c1+chromium-150.0.7871.187";
        public const int CEF_VERSION_MAJOR = 150;
        public const int CEF_COMMIT_NUMBER = 3558;
        public const string CEF_COMMIT_HASH = "3e666c1010f23897fd5076a78a15bec77c3ebdcf";
        
        public const int CHROME_VERSION_MAJOR = 150;
        public const int CHROME_VERSION_MINOR = 0;
        public const int CHROME_VERSION_BUILD = 7871;
        public const int CHROME_VERSION_PATCH = 187;
        
        public const int CEF_API_VERSION = 999999;
        public const string CEF_API_HASH_PLATFORM_WIN = "ee913e0bb46df4701ef4ae4b1b892a67e778c1ea";
        public const string CEF_API_HASH_PLATFORM_MACOS = "7ea42dda83baec118f92376b400833512e40a788";
        public const string CEF_API_HASH_PLATFORM_LINUX = "bd73ac8a3e1182dad89df48a632b2a1e59bf7c1c";
    }
}
