//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Runtime.InteropServices;
    using System.Diagnostics.CodeAnalysis;
    
    internal static unsafe partial class libcef
    {
        public const string CEF_VERSION = "150.0.23-2026-08-04-surface-lease.3556+ge7ab2e1+chromium-150.0.7871.187";
        public const int CEF_VERSION_MAJOR = 150;
        public const int CEF_COMMIT_NUMBER = 3556;
        public const string CEF_COMMIT_HASH = "e7ab2e15e1973d318458b5882a448be97ebd08c7";
        
        public const int CHROME_VERSION_MAJOR = 150;
        public const int CHROME_VERSION_MINOR = 0;
        public const int CHROME_VERSION_BUILD = 7871;
        public const int CHROME_VERSION_PATCH = 187;
        
        public const int CEF_API_VERSION = 999999;
        public const string CEF_API_HASH_PLATFORM_WIN = "98f8c0d3b73ee1ade0ea70e5e67f48116fa2b3f3";
        public const string CEF_API_HASH_PLATFORM_MACOS = "f7f0a19b29e2f1cb7dec42ee3ef26fc571da8a8e";
        public const string CEF_API_HASH_PLATFORM_LINUX = "8aba464ae9af72f65a1584199dd81fc3557c75b1";
    }
}
